#! /usr/bin/env bash

dmenu="dmenu -i -l 20 -p"

bookmarks="${HOME}/.config/qutebrowser/bookmarks/urls"
readarray -t bmarks < "$bookmarks"

quickmarks="${HOME}/.config/qutebrowser/quickmarks"
readarray -t qmarks < "$quickmarks"

history_db="${HOME}/.local/share/qutebrowser/history.sqlite"
sql="SELECT 'Qutebrowser', title, url FROM history where url like 'http%';"

bmlist=$(printf '%s\n' "${bmarks[@]}" | awk '{print $2" - "$1}' | sort)
qmlist=$(printf '%s\n' "${qmarks[@]}" | awk '{print "["$1"] - "$NF}' | sort)
htlist=$(printf '%s\n' "$(sqlite3 "$history_db" "${sql}")" | awk -F "|" '{print $1" - "$NF}')

main() {
    choice=$(printf '%s\n' "Quickmarks" "$qmlist"  "Bookmarks" "$bmlist" "History" "$htlist" | ${dmenu} 'Open:')

    if [ "$choice" == "Quickmarks" ] || [ "$choice" == "Bookmarks" ] || [ "$choice" == "History" ]; then
        qutebrowser

    elif [ "$choice" ]; then
        url=$(echo "${choice}" | awk '{print $NF}') || exit 1
        qutebrowser "$url"

    else
        echo "Program terminated." && exit 0

    fi
}

main
