#!/usr/bin/env bash

declare -A confedit
confedit[kitty]="$HOME/.config/kitty/"
confedit[fish]="$HOME/.config/fish/"
confedit[hyprland]="$HOME/.config/hypr/"
confedit[waybar]="$HOME/.config/waybar/"
confedit[startship]="$HOME/.config/starship.toml"
confedit[tmux]="$HOME/.config/tmux.conf"
confedit[bash]="$HOME/.bashrc"

dmenu="rofi -dmenu -p"

editor="nvim"

main() {
    declare -A clean_list

    for i in "${!confedit[@]}"; do
        [[ -e ${confedit["${i}"]} ]] && clean_list["${i}"]=${confedit["${i}"]}
    done

    choice=$(printf '%s\n' "${!clean_list[@]}" | sort | ${dmenu} 'Edit config:' "$@") || exit 1

    if [ "$choice" ]; then
        cfg=$(printf '%s\n' "${clean_list["${choice}"]}")
        $editor "$cfg"

    else
        echo "Program terminated." && exit 0
    fi
}

main
