#!/usr/bin/env bash

declare -A confedit
confedit[alacritty]="$HOME/.config/alacritty/alacritty.yml"
confedit[awesome]="$HOME/.config/awesome/rc.lua"
confedit[awesome theme]="$HOME/.config/awesome/theme.lua"
confedit[bash]="$HOME/.bashrc"
confedit[fish]="$HOME/.config/fish/config.fish"
confedit[nvim plugins]="$HOME/.config/nvim/lua/Nahuel/packer.lua"
confedit[nvim remap]="$HOME/.config/nvim/lua/Nahuel/remap.lua"
confedit[nvim set]="$HOME/.config/nvim/lua/Nahuel/set.lua"
confedit[nvim plugins configs]="$HOME/.config/nvim/after/plugin/"
confedit[qutebrowser bookmarks]="$HOME/.config/qutebrowser/urls"
confedit[qutebrowser quickmarks]="$HOME/.config/qutebrowser/quickmarks"
confedit[qutebrowser config.py]="$HOME/.config/qutebrowser/config.py"
confedit[xresources]="$HOME/.Xresources"
confedit[vifm]="$HOME/.config/vifm/vifmrc"
confedit[qtile]="$HOME/.config/qtile/config.py"
confedit[qtile autostart]="$HOME/.config/qtile/autostart.sh"
confedit[startship prompt]="$HOME/.config/starship.toml"

dmenu="dmenu -i -l 10 -g 3 -p"

editor="nvim"

main() {
    declare -A clean_list

    for i in "${!confedit[@]}"; do
        [[ -f ${confedit["${i}"]} ]] && clean_list["${i}"]=${confedit["${i}"]}
    done

    choice=$(printf '%s\n' "${!clean_list[@]}" | sort | ${dmenu} 'Edit config:' "$@") || exit 1

    if [ "$choice" ]; then
        cfg=$(printf '%s\n' "${clean_list["${choice}"]}")
        $editor "$cfg"

    else
        echo "Program terminated." && exit 0
    fi
}

main
