#!/usr/bin/env bash

declare -A confedit
confedit[alacritty]="$HOME/.config/alacritty/alacritty.toml"
confedit[awesome]="$HOME/.config/awesome/rc.lua"
confedit[awesome theme]="$HOME/.config/awesome/theme.lua"
confedit[bash]="$HOME/.bashrc"
confedit[fish]="$HOME/.config/fish/config.fish"
confedit[startship prompt]="$HOME/.config/starship.toml"
confedit[tmux]="$HOME/.config/tmux.conf"

dmenu="rofi -dmenu -p"

editor="nvim"

main() {
    declare -A clean_list

    for i in "${!confedit[@]}"; do
        [[ -f ${confedit["${i}"]} ]] && clean_list["${i}"]=${confedit["${i}"]}
    done

    choice=$(printf '%s\n' "${!clean_list[@]}" | sort | ${dmenu} 'Edit config:' "$@") || exit 1

    if [ "$choice" ]; then
        cfg=$(printf '%s\n' "${clean_list["${choice}"]}")
        $editor "$cfg"

    else
        echo "Program terminated." && exit 0
    fi
}

main
