#!/usr/bin/env bash

dmenu="dmenu -i -l 10 -g 3 -p"

pdf_viewer="zathura"

main() {
    directories=(
        "$HOME/Documentos/"
        "$HOME/Descargas/"
        "$HOME/Books/"
    )
    files="$(find "${directories[@]}" -maxdepth 5 -iname "*.pdf")"

    if [[ -z "$files" ]]; then
        echo "No PDF files found in specified directories."
        exit 1
    fi

    choice=$(printf '%s\n' "${files[@]}" | \
           ${dmenu} "File:" "$@") || exit 1

    notify-send $choice

    if [ -n "$choice" ]; then
        "${pdf_viewer}" "$choice"

    else
        echo "Program terminated." && exit 0
    fi
}

main
