#! /usr/bin/env bash

# dmenu prints the options in insensitive mode, 20 options and prompt it something.
dmenu="dmenu -i -l 20 -p"

main() {
    # Running ps to get running processes and display in dmenu.
    selected="$(ps --user  "$USER" -F | \
              ${dmenu} 'Search a process to kill:' "$@" | \
              awk '{print $2" "$11}')";

    # Nested 'if' statements.  The outer 'if' statement is what to do
    # when we select one of the 'selected' options listed in dmenu.
    if [[ -n $selected ]]; then
        # Piping No/Yes into dmenu as a safety measure.
        answer="$(echo -e "No\nYes" | ${dmenu} "Kill $selected?" "$@")"

        if [[ $answer == "Yes" ]]; then
            kill -9 "${selected%% *}"
            echo "Process $selected has been killed." && exit 0

        # I want this script to exit with a 1 and not 0 because 1 means
	    # an error, so this can be handled by other scripts better.
        else
            echo "Program terminated." && exit 1
        fi
    fi
}

main
