#! /usr/bin/env bash

dmenu="rofi -dmenu -i -l 10 -p"

main() {
    selected="$(ps --user  "$USER" -F | \
              ${dmenu} 'Search a process to kill ' "$@" | \
              awk '{print $2" "$11}')";

    if [[ -n $selected ]]; then
        answer="$(echo -e "No\nYes" | ${dmenu} "Kill $selected?" "$@")"

        if [[ $answer == "Yes" ]]; then
            kill -9 "${selected%% *}"
            echo "Process $selected has been killed." && exit 0

        else
            echo "Program terminated." && exit 1
        fi
    fi
}

main
