#! /usr/bin/env bash

dmenu="rofi -dmenu -p"

declare -a options=(
"Quit"
"Reboot"
"Shutdown"
)

main() {
    choice=$(printf '%s\n' "${options[@]}" | ${dmenu} 'Menu:' "${@}")

    case $choice in
        'Reboot')
            if [[ "$(echo -e "No\nYes" | ${dmenu} "${choice}?" "${@}")" == "Yes" ]]; then
                systemctl reboot

            fi
        ;;

        'Shutdown')
            if [[ "$(echo -e "No\nYes" | ${dmenu} "${choice}?" "${@}")" == "Yes" ]]; then
                systemctl poweroff

            fi
        ;;

        *)
            exit 1
        ;;
    esac
}

main
