#! /usr/bin/env bash

dmenu="rofi -dmenu -i -p"

options=(
    'Quit'
    'Reboot'
    'Shutdown'
)

main() {
    choice=$(printf '%s\n' "${options[@]}" | ${dmenu} 'Menu:' "${@}")

    case $choice in
        'Reboot')
            if [[ "$(echo -e "No\nYes" | ${dmenu} "${choice}?" "${@}")" == "Yes" ]]; then
                systemctl reboot
            else
                echo "Reboot cancelled." && exit 1
            fi
        ;;

        'Shutdown')
            if [[ "$(echo -e "No\nYes" | ${dmenu} "${choice}?" "${@}")" == "Yes" ]]; then
                systemctl poweroff
            else
                echo "Shutdown cancelled." && exit 1
            fi
        ;;

        *)
            echo "User choose to close" && exit 1
        ;;
    esac
}

main
