#!/usr/bin/env bash

declare -A radio_stations
radio_stations[Aspen]="https://tunein.com/radio/Aspen-1023-(Buenos-Aires)-s25905/"
radio_stations[LaNacion]="https://masmusica.lanacion.com.ar/"

dmenu="rofi -dmenu -i -p"
RADIO_VOLUME="70"

menu() {
    printf '%s\n' "Quit"
    printf '%s\n' "${!radio_stations[@]}" | sort
}

start_radio() {
  notify-send "Starting dm-radio" "Playing station: $1. 🎶"
}

end_radio() {
  notify-send "Stopping dm-radio" "You have quit dm-radio. 🎶"
}

main() {
    choice=$(menu | ${dmenu} 'Choose radio station:' "$@") || exit 1

    case $choice in
    Quit)
        end_radio;
        pkill -f http
        exit
        ;;

    *)
        pkill -f http || echo "mpv not running."
        start_radio "$choice" ;
        mpv "${radio_stations["${choice}"]}" --volume="${RADIO_VOLUME:-100}"
        return
        ;;
    esac
}

main
