#!/usr/bin/env bash

# You'll need arch-wiki-docs installed to work
wikiDir="/usr/share/doc/arch-wiki/html/en/"

wikiDocs="$(find ${wikiDir} -iname "*.html")"

browser="qutebrowser"

dmenu="dmenu -i -l 10 -g 3 -p"

main() {
    choice=$(printf '%s\n' "${wikiDocs[@]}" | \
        cut -d '/' -f8- | \
        sed -e 's/_/ /g' -e 's/.html//g' | \
        sort -g | \
        ${dmenu} 'Arch wiki docs:') || exit 1

    if [ "${choice}" ]; then
        article=$(printf '%s\n' "${wikiDir}${choice}.html" | sed 's/ /_/g')
        "$browser" "$article"

    else
        echo "Program terminated." && exit 0
    fi
}

main
