#!/usr/bin/env bash

rofi="rofi -dmenu -i -p"
player="mpv --force-window=immediate --volume=100 --ontop"
        

declare -A youtube_channels
youtube_channels[distrotube]="https://www.youtube.com/c/DistroTube/videos"
youtube_channels[Brodie Robertson]="https://www.youtube.com/@BrodieRobertson/videos"
youtube_channels[The Linux Experiment]="https://www.youtube.com/@TheLinuxEXP/videos"
youtube_channels[ThePrimeagen]="https://www.youtube.com/@ThePrimeagen/videos"
youtube_channels[ThePrimeTime]="https://www.youtube.com/@ThePrimeTimeagen/videos"
youtube_channels[Fireship]="https://www.youtube.com/@Fireship/videos"
youtube_channels[Web Dev Cody]="https://www.youtube.com/@WebDevCody/videos"
youtube_channels[TJ DeVries]="https://www.youtube.com/@teej_dv/videos"
youtube_channels[TechLead]="https://www.youtube.com/@TechLead/videos"
youtube_channels[Chris Titus Tech]="https://www.youtube.com/@ChrisTitusTech/videos"
youtube_channels[Antonio Sarosi]="https://www.youtube.com/@AntonioSarosi/videos"
youtube_channels[Nate Gentile]="https://www.youtube.com/@NateGentile7/videos"
youtube_channels[midulive]="https://www.youtube.com/@midulive/videos"
youtube_channels[midudev]="https://www.youtube.com/@midudev/videos"
youtube_channels[bilinks]="https://www.youtube.com/@bilinkis/videos"
youtube_channels[CodelyTV]="https://www.youtube.com/@CodelyTV/videos"
youtube_channels[HolaMundoDev]="https://www.youtube.com/@HolaMundoDev/videos"
youtube_channels[b001]="https://www.youtube.com/@b001/videos"
youtube_channels[theo]="https://www.youtube.com/@t3dotgg/videos"
youtube_channels[TsodingDaily]="https://www.youtube.com/@TsodingDaily/videos"
youtube_channels[Tsoding]="https://www.youtube.com/@Tsoding/videos"

xmlgetnext () {
  local IFS='>'
  read -d '<' TAG VALUE
}

parse_rss() {
  echo "$1" | while xmlgetnext ; do
    case $TAG in
        'entry')
          title=''
          link=''
          published=''
          ;;
        'media:title')
          title="$VALUE"
          ;;
        'yt:videoId')
          link="$VALUE"
          ;;
        'published')
          published="$(date --date="${VALUE}" "+%Y-%m-%d %H:%M")"
            ;;
        '/entry')
          echo " ${published} | ${link} | ${title}"
          ;;
        esac
  done
}

main() {
  local _feed_url _channel _video_title _selected_title
  local _channel_id _video_id _video_list
  declare -A video_map

  _channel=$(printf '%s\n' "${!youtube_channels[@]}" | sort | ${rofi} 'Select Channel:' "$@")

  _channel_id=$(curl -s -f -L "${youtube_channels[${_channel}]}" | grep -o "channel_id=.*" | sed 's/".*//g')
  _feed_url="https://www.youtube.com/feeds/videos.xml?channel_id=${_channel_id##*=}"
  _video_list=$(parse_rss "$(curl -s "${_feed_url}")" )

  declare -a video_titles
  declare -a video_ids
  
  while IFS= read -r line; do
    if [[ -n "$line" && "$line" =~ \|.*\|.* ]]; then
      _video_id=$(echo "$line" | cut -d'|' -f2 | sed -e 's/^[ \t]*//')
      _video_title=$(echo "$line" | cut -d'|' -f3 | sed -e 's/^[ \t]*//' -e 's/["]//g')
      
      if [[ -n "$_video_id" && -n "$_video_title" ]]; then
        video_titles+=("$_video_title")
        video_ids+=("$_video_id")
        video_map["$_video_title"]="$_video_id"
      fi
    fi
  done <<< "$(echo "$_video_list" | sort -r)"

  local max_videos=${#video_titles[@]}
  if [[ $max_videos -gt 15 ]]; then
    max_videos=15
  fi

  local titles_to_show=()
  for ((i=0; i<$max_videos; i++)); do
    titles_to_show+=("${video_titles[$i]}")
  done

  _selected_title=$(printf '%s\n' "${titles_to_show[@]}" | ${rofi} "Select Video (${max_videos} available)" "$@")
  
  _video_id="${video_map[$_selected_title]}"

  if [[ -n ${_video_id} ]]; then
    ${player} --title="${_selected_title}" \
        "https://www.youtube.com/watch?v=${_video_id}"
  fi
}

main
