#!/usr/bin/env bash

dmenu="rofi -dmenu -i -p"
browser="brave"

declare -A youtube_channels
youtube_channels[distrotube]="https://www.youtube.com/c/DistroTube/featured"
youtube_channels[Brodie Robertson]="https://www.youtube.com/@BrodieRobertson/featured"
youtube_channels[The Linux Experiment]="https://www.youtube.com/@TheLinuxEXP/featured"
youtube_channels[ThePrimeagen]="https://www.youtube.com/@ThePrimeagen/featured"
youtube_channels[ThePrimeTime]="https://www.youtube.com/@ThePrimeTimeagen/featured"
youtube_channels[Fireship]="https://www.youtube.com/@Fireship/featured"
youtube_channels[Web Dev Cody]="https://www.youtube.com/@WebDevCody/featured"
youtube_channels[TJ DeVries]="https://www.youtube.com/@teej_dv/featured"
youtube_channels[TechLead]="https://www.youtube.com/@TechLead/featured"
youtube_channels[Chris Titus Tech]="https://www.youtube.com/@ChrisTitusTech/featured"
youtube_channels[Antonio Sarosi]="https://www.youtube.com/@AntonioSarosi/featured"
youtube_channels[Nate Gentile]="https://www.youtube.com/@NateGentile7/featured"
youtube_channels[midulive]="https://www.youtube.com/@midulive/featured"
youtube_channels[midudev]="https://www.youtube.com/@midudev/featured"
youtube_channels[tsodingdaily]="https://www.youtube.com/@TsodingDaily/featured"
youtube_channels[bilinks]="https://www.youtube.com/@bilinkis/featured"
youtube_channels[CodelyTV]="https://www.youtube.com/@CodelyTV/featured"
youtube_channels[HolaMundoDev]="https://www.youtube.com/@HolaMundoDev/featured"
youtube_channels[b001]="https://www.youtube.com/@b001/featured"

xmlgetnext () {
  local IFS='>'
  read -d '<' TAG VALUE
}

parse_rss() {
  echo "$1" | while xmlgetnext ; do
    case $TAG in
        'entry')
          title=''
          link=''
          published=''
          ;;
        'media:title')
          title="$VALUE"
          ;;
        'yt:videoId')
          link="$VALUE"
          ;;
        'published')
          published="$(date --date="${VALUE}" "+%Y-%m-%d %H:%M")"
            ;;
        '/entry')
          echo " ${published} | ${link} | ${title}"
          ;;
        esac
  done
}

main() {
  local _feed_url _channel _video
  local _channel_id _video_id _video_list

  _channel=$(printf '%s\n' "${!youtube_channels[@]}" | sort | ${dmenu} 'Select Channel:' "$@")

  _channel_id=$(curl -s -f -L "${youtube_channels[${_channel}]}" | grep -o "channel_id=.*" | sed 's/".*//g')
  _feed_url="https://www.youtube.com/feeds/videos.xml?channel_id=${_channel_id##*=}"
  _video_list=$(parse_rss "$(curl -s "${_feed_url}")" )

  _video=$(printf '%s\n' "${_video_list}" | sort -r | ${dmenu} 'Select Video' "$@")
  _video_id=$(echo "${_video}" | cut -d'|' -f2 | sed -e 's/^[ \t]*//')

  if [[ -n ${_video_id} ]]; then
    ${browser} "https://www.youtube.com/watch?v=${_video_id}"
  fi
}

main
